version: 6.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

install:
  ps: |
    $versionPrefix = [Version]$Env:APPVEYOR_BUILD_VERSION
    $prNumber = $Env:APPVEYOR_PULL_REQUEST_NUMBER
    $sourceBranch = $Env:APPVEYOR_REPO_BRANCH
    $sourceCommit = $Env:APPVEYOR_REPO_COMMIT.Substring(0,8)
    if ($prNumber)
    {
      $versionLabel = "pr${prNumber}"
      $versionSuffix = "-${versionLabel}+$sourceCommit"
    }
    elseif ($sourceBranch.StartsWith('release') -Or $sourceBranch.StartsWith('hotfix'))
    {
      $versionLabel = "rc"
      $versionSuffix = "-$versionLabel-$buildNumber+$sourceCommit"
    }
    elseif ($sourceBranch -ne 'master')
    {
      $versionLabel = "dev"
      $versionSuffix = "-$versionLabel-$buildNumber+$sourceCommit"
    }
    else
    {
      $versionSuffix = ""
    }
    $version = "$versionPrefix$versionSuffix"
    Write-Host "Version set to: $version"
    Add-AppveyorMessage -Message "Version set to: $version" -Category Information
    Update-AppveyorBuild -Version "$version"

configuration: Release

before_build:
  - nuget restore WpfToolkit\WPFToolkit.sln

build:
  project: 'WpfToolkit\WPFToolkit.sln'

test: off

artifacts:
  - path: '**\bin\$(configuration)\net40\DotNetProjects.*.dll'
  - path: '**\bin\$(configuration)\net40\DotNetProjects.*.pdb'
  - path: '**\bin\$(configuration)\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
