version: 6.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019 Preview

install:
  - cmd: choco install dotnetcore-sdk --pre

configuration: Release

before_build:
  - nuget restore WpfToolkit\WPFToolkit.sln

build:
  project: 'WpfToolkit\WPFToolkit.sln'

test: off

artifacts:
  - path: '**\bin\$(configuration)\net40\DotNetProjects.*.dll'
  - path: '**\bin\$(configuration)\net40\DotNetProjects.*.pdb'
  - path: '**\bin\$(configuration)\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
